eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway

server:
  port: 9000


zuul:
  routes:
    order-server: /apigateway/order/**
  ignored-patterns: /*-server/**
  sensitive-headers:
