
    #zipkin服务所在地址
zipkin:
  base-url:  http://106.14.14.196:9411/
    #配置采样百分比 默认是0.1  改成1就是全部  开发环境可以设置为1  生产就用默认的
  sleuth:
    sampler:
      probability: 1
spring:      
  rabbitmq:
    host: 106.14.14.196
    username: guest
    password: guest
    port: 5672
  main:
    allow-bean-definition-overriding: true

    #暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true
