spring:
  rabbitmq:
    port: 5672
    host: 106.14.14.196
    username: guest
    password: guest
server:
  port: 9876



#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
env:master-test

